name: Deploy

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Initialize
        run: yarn bootstrap
      - name: Run build server
        run: yarn build --scope=server
      - name: Run build client ssr
        run: yarn lerna run --scope=client build:ssr

  push_to_yandex_registry:
    runs-on: ubuntu-latest
    needs: [build_test]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.YANDEX_REGISTRY_USERNAME }}
          password: ${{ secrets.YANDEX_REGISTRY_TOKEN }}

      - name: Docker build
        run: docker compose -f ./docker-compose.build.yml build --no-cache
      - name: Docker push
        run: docker compose -f ./docker-compose.build.yml push

  deploy:
    runs-on: ubuntu-latest   
    needs: [push_to_yandex_registry]
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          password: ${{ secrets.VPS_SSH_PASSWORD }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Pull new image"
            docker-compose -f /home/${{ secrets.VPS_SSH_USERNAME }}/praktikum-team-07/docker-compose.yml pull
            echo "Restart the container"
            docker-compose -f /home/${{ secrets.VPS_SSH_USERNAME }}/praktikum-team-07/docker-compose.yml up --force-recreate --build --no-deps -d
            echo "Delete old image"
            docker image prune -f