name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install and Initialize
        run: yarn bootstrap
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Run build server
        run: yarn build --scope=server
      - name: Run build client ssr
        run: yarn lerna run --scope=client build:ssr

  push_to_yandex_registry:
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: 'cr.yandex'
          username: ${{ secrets.YANDEX_REGISTRY_USERNAME }}
          password: ${{ secrets.YANDEX_REGISTRY_KEY }}

      - name: Copy env
        run: cp .env.sample .env
      - name: Docker build
        run: docker compose -f ./docker-compose.build.yml build --no-cache
      - name: Docker push
        run: docker compose -f ./docker-compose.build.yml push

  deploy:
    runs-on: ubuntu-latest   
    needs: [push_to_yandex_registry]
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          YANDEX_REGISTRY_KEY: ${{ secrets.YANDEX_REGISTRY_KEY }}
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script_stop: true
          envs: YANDEX_REGISTRY_KEY
          script: |
            cd /home/${{ secrets.VPS_SSH_USERNAME }}/praktikum-team-07
            echo "Pull main branch"
            git pull origin main
            echo "Docker login"
            echo "$YANDEX_REGISTRY_KEY" | docker login --username='${{secrets.YANDEX_REGISTRY_USERNAME}}' --password-stdin cr.yandex
            echo "Pull new docker image"
            docker compose -f ./docker-compose.yml pull
            echo "Restart the container"
            CURRENT_USER=$(id -u):$(id -g) docker compose -f ./docker-compose.yml up --force-recreate --build --no-deps -d
            echo "Delete old image"
            docker image prune -f
            echo "Docker logout"
            docker logout
            echo "Done"